version: '3'

services:
  web:
    image: mavidoc/my-web-app:latest
    ports:
      - "80:80"
    container_name: my_web_app
    restart: always

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
    restart: always