version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
    container_name: my_web_app

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower